Update schedule-crawler-by-api.yml

diff --git a/.github/workflows/schedule-crawler-by-api.yml b/.github/workflows/schedule-crawler-by-api.yml
--- a/.github/workflows/schedule-crawler-by-api.yml
+++ b/.github/workflows/schedule-crawler-by-api.yml
@@ -76,18 +76,33 @@ jobs:
           echo "const {crawlData} = require('./crawls/crawl-by-api'); crawlData(${{ matrix.os.chunk }});" > main.js
           node main.js
 
-      - name: Push changes
+      - name: Switch git user to github action.
+        working-directory: nestjs-carz-crawler-action
         run: |
-          du -h ./${{ matrix.os.chunk }}.cars-data-crawler.csv
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-          git push origin --delete feat/data-crawler-${{ matrix.os.chunk }} || echo "Error"
-          git branch -d feat/data-crawler-${{ matrix.os.chunk }} || echo "Error"
-          git checkout -b feat/data-crawler-${{ matrix.os.chunk }}
-          git add ./${{ matrix.os.chunk }}.cars-data-crawler.csv
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Switch to new Branch.
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git push origin --delete chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
+          git checkout --orphan chunk/data-crawler-${{ matrix.machine.chunk }}
+          git reset
+
+      - name: Copy file
+        run: |
+          if [ -e "nestjs-carz-crawler/${{ matrix.machine.chunk }}.cars-data-crawler.csv" ]; then
+            cp nestjs-carz-crawler/${{ matrix.machine.chunk }}.cars-data-crawler.csv nestjs-carz-crawler-action/
+          else
+            touch nestjs-carz-crawler-action/${{ matrix.machine.chunk }}.cars-data-crawler.csv
+          fi
+
+      - name: Push to chunk/data-crawler-${{ matrix.machine.chunk }}.
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git add ${{ matrix.machine.chunk }}.cars-data-crawler.csv
           git commit -m "✅ - Save crawler data."
-          git push --set-upstream origin feat/data-crawler-${{ matrix.os.chunk }} || echo "Error"
-          cat ./${{ matrix.os.chunk }}.cars-data-crawler.csv
+          git push origin chunk/data-crawler-${{ matrix.machine.chunk }}
 
       - name: Failure notification
         if: ${{ failure() }}
