Update schedule-crawler-by-api.yml

diff --git a/.github/workflows/schedule-crawler-by-api.yml b/.github/workflows/schedule-crawler-by-api.yml
--- a/.github/workflows/schedule-crawler-by-api.yml
+++ b/.github/workflows/schedule-crawler-by-api.yml
@@ -102,9 +102,63 @@ jobs:
     name: Send Notification Result
     runs-on: ubuntu-latest
     steps:
-      - name: Succesfully notification
-        uses: appleboy/telegram-action@master
+      after-crawler:
+    needs: [pre-crawler, crawler]
+    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
+    name: After Crawler
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clone nestjs-carz-crawler-action.
+        uses: actions/checkout@v4
         with:
-          to: ${{ secrets.TELEGRAM_CHANNEL }}
-          token: ${{ secrets.TELEGRAM_TOKEN }}
-          message: "✅ - Success crawling data by API."
+          token: ${{ secrets.GH_TOKEN }}
+          path: nestjs-carz-crawler-action
+          ref: main
+
+      - name: Cleaup.
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          rm -rf data
+          mkdir data
+
+      - name: Loop clone.
+        run: |
+          for i in {1..${{ needs.pre-crawler.outputs.number-machines }}}
+          do
+            git clone -b chunk/data-crawler-$i  https://LibertyCarz:${{ secrets.GH_TOKEN }}@github.com/LibertyCarz/nestjs-carz-crawler-action.git chunk-$i
+            cp chunk-$i/$i.cars-data-crawler.csv nestjs-carz-crawler-action/data/
+          done
+
+      - name: Merge files
+        working-directory: nestjs-carz-crawler-action/data
+        run: |
+          cat 1.cars-data-crawler.csv >>cars-data-crawler.csv
+          for i in {2..${{needs.pre-crawler.outputs.number-machines}}};
+          do
+            tail -n +2 "$i.cars-data-crawler.csv" >>cars-data-crawler.csv
+          done
+
+      - name: Switch git user to github action.
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Push
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git add -A
+          git commit -m "✅ - Save crawler data."
+          git push origin main || echo "Error"
+
+      - name: Remove Chunk branch
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git fetch
+          git branch -r | grep 'origin' | grep -v 'main$' | grep -v HEAD | cut -d/ -f2- | while read line; do git push origin :heads/$line; done;
+
+      - name: Notification to telegram
+        uses: PacificPromise/macos-telegram-action@main
+        with:
+          type: topic
+          message: "✅ Success crawling data Khmer24: ${{ needs.pre-crawler.outputs.message }}"
