Update schedule-crawler-by-api.yml

diff --git a/.github/workflows/schedule-crawler-by-api.yml b/.github/workflows/schedule-crawler-by-api.yml
--- a/.github/workflows/schedule-crawler-by-api.yml
+++ b/.github/workflows/schedule-crawler-by-api.yml
@@ -6,74 +6,101 @@ on:
 
   workflow_dispatch:
     inputs:
-      reason:
-        description: "Fill reason here!!!!!!"
-        required: false
+      number-machines:
+        description: "Total number of machines"
+        required: True
+        default: "21"
 permissions:
   contents: write
   actions: write
 jobs:
-  pre-deployment:
-    name: Pre Deployment
+  pre-crawler:
+    name: Pre Crawler
     runs-on: ubuntu-latest
+    timeout-minutes: 1
+    outputs:
+      number-machines: ${{ steps.number-machines.outputs.value }}
+      matrix: ${{ steps.matrix.outputs.value }}
+      message: ${{ steps.message-information.outputs.value }}
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Calculation inputs number machines.
+        id: number-machines
+        run: |
+          NUMBER=20
+          if [ "${{ github.event.inputs.number-machines }}" ]; then
+            NUMBER=${{ github.event.inputs.number-machines }}
+          fi
+          echo "value=$NUMBER" >> $GITHUB_OUTPUT
+
+      - name: Calculation machines.
+        id: matrix
+        run: |
+          MATRIX="{\"name\":\"ubuntu-latest\",\"chunk\":1}"
+          for i in {2..${{ steps.number-machines.outputs.value }}}
+          do
+            MATRIX="$MATRIX,{\"name\":\"ubuntu-latest\",\"chunk\":$i}"
+          done
+          echo "value=[ $MATRIX ]" >> $GITHUB_OUTPUT
+
+      - name: Generate message
+        id: message-information
+        run: |
+          source .github/scripts/utils.sh
+          echo "value=$(get_message_information)" >> "$GITHUB_OUTPUT"
+
       - name: Notification to telegram
-        uses: appleboy/telegram-action@master
+        uses: PacificPromise/macos-telegram-action@main
         with:
-          to: ${{ secrets.TELEGRAM_CHANNEL }}
-          token: ${{ secrets.TELEGRAM_TOKEN }}
-          message: "🚀 - Start crawling data by API..."
+          type: topic
+          message: "🚀 Start crawling data Khmer24: ${{ steps.message-information.outputs.value }}"
+
+      - name: Echo all value.
+        run: |
+          echo "Number of machines: ${{ steps.number-machines.outputs.value }}"
+          echo "Message: ${{ steps.message-information.outputs.value }}"
+          echo "Matrix: ${{ steps.matrix.outputs.value }}"
+
   crawler:
-    needs: [pre-deployment]
+    needs: [pre-crawler]
     continue-on-error: true
     strategy:
-      fail-fast: true
+      # fail-fast: true
       matrix:
-        os:
-          [
-            { name: ubuntu-latest, chunk: 0 },
-            { name: ubuntu-latest, chunk: 1 },
-            { name: ubuntu-latest, chunk: 2 },
-            { name: ubuntu-latest, chunk: 3 },
-            { name: ubuntu-latest, chunk: 4 },
-            { name: ubuntu-latest, chunk: 5 },
-            { name: ubuntu-latest, chunk: 6 },
-            { name: ubuntu-latest, chunk: 7 },
-            { name: ubuntu-latest, chunk: 8 },
-            { name: ubuntu-latest, chunk: 9 },
-            { name: ubuntu-latest, chunk: 10 },
-            { name: ubuntu-latest, chunk: 11 },
-            { name: ubuntu-latest, chunk: 12 },
-            { name: ubuntu-latest, chunk: 13 },
-            { name: ubuntu-latest, chunk: 14 },
-            { name: ubuntu-latest, chunk: 15 },
-            { name: ubuntu-latest, chunk: 16 },
-            { name: ubuntu-latest, chunk: 17 },
-            { name: ubuntu-latest, chunk: 18 },
-            { name: ubuntu-latest, chunk: 19 },
-            { name: ubuntu-latest, chunk: 20 },
-          ]
-    runs-on: ${{ matrix.os.name }}
+        machine: ${{ fromJson(needs.pre-crawler.outputs.matrix) }}
+    runs-on: ${{ matrix.machine.name }}
     steps:
-      - name: Clone repository
-        uses: actions/checkout@v3
+      - name: Check IP
+        run: curl https://ipinfo.io/ip || echo "Error"
+
+      - name: Clone nestjs-carz-crawler-action.
+        uses: actions/checkout@v4
         with:
-          repository: "LibertyCarz/nestjs-carz-crawler"
           token: ${{ secrets.GH_TOKEN }}
-          ref: "main"
+          path: nestjs-carz-crawler-action
+          ref: main
+
+      - name: Clone repository nestjs-carz-crawler.
+        uses: actions/checkout@v4
+        with:
+          repository: LibertyCarz/nestjs-carz-crawler
+          token: ${{ secrets.GH_TOKEN }}
+          path: nestjs-carz-crawler
+          ref: main
+  
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 18.12.0
 
-      # - name: Install dependencies
-      #   run: npm install --force
-
       - name: Start NestJS application
+        working-directory: nestjs-carz-crawler
         run: |
           node -v
-          echo "const {crawlData} = require('./crawls/crawl-by-api'); crawlData(${{ matrix.os.chunk }});" > main.js
+          echo "const {crawlData} = require('./crawls/crawl-by-api'); crawlData(${{ matrix.machine.chunk }});" > main.js
           node main.js
 
       - name: Switch git user to github action.
@@ -110,70 +137,65 @@ jobs:
         with:
           to: ${{ secrets.TELEGRAM_CHANNEL }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
-          message: "💣 - Failure crawling data by API(${{ matrix.os.chunk }})."
+          message: "💣 - Failure crawling data by API(${{ matrix.machine.chunk }})."
 
-  finish:
-    needs: [crawler]
-    name: Send Notification Result
+  after-crawler:
+    needs: [crawler, pre-crawler]
+    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
+    name: After Crawler
     runs-on: ubuntu-latest
     steps:
-      after-crawler:
-      needs: [pre-crawler, crawler]
-      if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
-      name: After Crawler
-      runs-on: ubuntu-latest
-      steps:
-        - name: Clone nestjs-carz-crawler-action.
-          uses: actions/checkout@v4
-          with:
-            token: ${{ secrets.GH_TOKEN }}
-            path: nestjs-carz-crawler-action
-            ref: main
-  
-        - name: Cleaup.
-          working-directory: nestjs-carz-crawler-action
-          run: |
-            rm -rf data
-            mkdir data
-  
-        - name: Loop clone.
-          run: |
-            for i in {1..${{ needs.pre-crawler.outputs.number-machines }}}
-            do
-              git clone -b chunk/data-crawler-$i  https://LibertyCarz:${{ secrets.GH_TOKEN }}@github.com/LibertyCarz/nestjs-carz-crawler-action.git chunk-$i
-              cp chunk-$i/$i.cars-data-crawler.csv nestjs-carz-crawler-action/data/
-            done
-  
-        - name: Merge files
-          working-directory: nestjs-carz-crawler-action/data
-          run: |
-            cat 1.cars-data-crawler.csv >>cars-data-crawler.csv
-            for i in {2..${{needs.pre-crawler.outputs.number-machines}}};
-            do
-              tail -n +2 "$i.cars-data-crawler.csv" >>cars-data-crawler.csv
-            done
-  
-        - name: Switch git user to github action.
-          working-directory: nestjs-carz-crawler-action
-          run: |
-            git config --global user.name "GitHub Actions"
-            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-  
-        - name: Push
-          working-directory: nestjs-carz-crawler-action
-          run: |
-            git add -A
-            git commit -m "✅ - Save crawler data."
-            git push origin main || echo "Error"
-  
-        - name: Remove Chunk branch
-          working-directory: nestjs-carz-crawler-action
-          run: |
-            git fetch
-            git branch -r | grep 'origin' | grep -v 'main$' | grep -v HEAD | cut -d/ -f2- | while read line; do git push origin :heads/$line; done;
-  
-        - name: Notification to telegram
-          uses: PacificPromise/macos-telegram-action@main
-          with:
-            type: topic
-            message: "✅ Success crawling data Khmer24: ${{ needs.pre-crawler.outputs.message }}"
+      - name: Clone nestjs-carz-crawler-action.
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GH_TOKEN }}
+          path: nestjs-carz-crawler-action
+          ref: main
+
+      - name: Cleaup.
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          rm -rf data
+          mkdir data
+
+      - name: Loop clone.
+        run: |
+          for i in {1..${{ needs.pre-crawler.outputs.number-machines }}}
+          do
+            git clone -b chunk/data-crawler-$i  https://LibertyCarz:${{ secrets.GH_TOKEN }}@github.com/LibertyCarz/nestjs-carz-crawler-action.git chunk-$i
+            cp chunk-$i/$i.cars-data-crawler.csv nestjs-carz-crawler-action/data/
+          done
+
+      - name: Merge files
+        working-directory: nestjs-carz-crawler-action/data
+        run: |
+          cat 1.cars-data-crawler.csv >>cars-data-crawler.csv
+          for i in {2..${{needs.pre-crawler.outputs.number-machines}}};
+          do
+            tail -n +2 "$i.cars-data-crawler.csv" >>cars-data-crawler.csv
+          done
+
+      - name: Switch git user to github action.
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Push
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git add -A
+          git commit -m "✅ - Save crawler data."
+          git push origin main || echo "Error"
+
+      - name: Remove Chunk branch
+        working-directory: nestjs-carz-crawler-action
+        run: |
+          git fetch
+          git branch -r | grep 'origin' | grep -v 'main$' | grep -v HEAD | cut -d/ -f2- | while read line; do git push origin :heads/$line; done;
+
+      - name: Notification to telegram
+        uses: PacificPromise/macos-telegram-action@main
+        with:
+          type: topic
+          message: "✅ Success crawling data Khmer24: ${{ needs.pre-crawler.outputs.message }}"
