ci: add merge step

diff --git a/.github/workflows/schedule-crawler.yml b/.github/workflows/schedule-crawler.yml
--- a/.github/workflows/schedule-crawler.yml
+++ b/.github/workflows/schedule-crawler.yml
@@ -20,7 +20,7 @@ permissions:
 
 jobs:
   pre-crawler:
-    name: Pre Deployment
+    name: Pre Crawler
     runs-on: ubuntu-latest
     outputs:
       number-machines: ${{ steps.number-machines.outputs.value }}
@@ -57,14 +57,95 @@ jobs:
       #     token: ${{ secrets.TELEGRAM_TOKEN }}
       #     message: "🚀 - Start crawling data Khmer24..."
 
-  crawler:
+  # crawler:
+  #   name: Crawler
+  #   needs: [pre-crawler]
+  #   continue-on-error: true
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       machine: ${{ fromJson(needs.pre-crawler.outputs.matrix) }}
+  #   runs-on: ${{ matrix.machine.name }}
+  #   steps:
+  #     - name: Clone nestjs-carz-crawler-action.
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
+  #         path: nestjs-carz-crawler-action
+  #         ref: main
+
+  #     - name: Clone repository nestjs-carz-crawler.
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: LibertyCarz/nestjs-carz-crawler
+  #         token: ${{ secrets.GH_TOKEN }}
+  #         path: nestjs-carz-crawler
+  #         ref: main
+
+  #     - name: Set up Node.js.
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 18.12.0
+
+  #     - name: Install dependencies.
+  #       working-directory: nestjs-carz-crawler
+  #       run: npm install --force
+
+  #     - name: Start NestJS application.
+  #       working-directory: nestjs-carz-crawler
+  #       run: |
+  #         node -v
+  #         echo "const crawler = require('./crawl'); crawler.createData(${{ matrix.machine.chunk }});" > crawler${{ matrix.machine.chunk }}.js
+  #         node crawler${{ matrix.machine.chunk }}
+
+  #     - name: Switch git user to github action.
+  #       working-directory: nestjs-carz-crawler-action
+  #       run: |
+  #         git config --global user.name "GitHub Actions"
+  #         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+  #     - name: Switch to new Branch.
+  #       working-directory: nestjs-carz-crawler-action
+  #       run: |
+  #         git push origin --delete chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
+  #         git checkout --orphan chunk/data-crawler-${{ matrix.machine.chunk }}
+
+  #     - name: Copy file.
+  #       run: cp nestjs-carz-crawler/${{ matrix.machine.chunk }}.cars-data-crawler.csv nestjs-carz-crawler-action/
+
+  #     - name: Push to chunk/data-crawler-${{ matrix.machine.chunk }}.
+  #       working-directory: nestjs-carz-crawler-action
+  #       run: |
+  #         git add ${{ matrix.machine.chunk }}.cars-data-crawler.csv
+  #         git commit -m "✅ - Save crawler data."
+  #         git push origin chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
+
+  # - name: Push changes
+  #   run: |
+  #     du -h ./${{ matrix.machine.chunk }}.cars-data-crawler.csv
+  #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
+  #     git config --global user.name "github-actions[bot]"
+  #     git push origin --delete feat-t/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
+  #     git checkout --orphan feat-t/data-crawler-${{ matrix.machine.chunk }}
+  #     git add ./${{ matrix.machine.chunk }}.cars-data-crawler.csv
+  #     git commit -m "✅ - Save crawler data."
+  #     git push origin feat-t/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
+  #     cat ./${{ matrix.machine.chunk }}.cars-data-crawler.csv
+
+  # - name: Failure notification
+  #   if: ${{ failure() }}
+  #   uses: appleboy/telegram-action@master
+  #   with:
+  #     to: ${{ secrets.TELEGRAM_CHANNEL }}
+  #     token: ${{ secrets.TELEGRAM_TOKEN }}
+  #     message: "💣 - Failure crawling data Khmer24(${{ matrix.machine.chunk }})."
+
+  after-crawler:
+    # needs: [pre-crawler, crawler]
     needs: [pre-crawler]
-    continue-on-error: true
-    strategy:
-      fail-fast: true
-      matrix:
-        machine: ${{ fromJson(needs.pre-crawler.outputs.matrix) }}
-    runs-on: ${{ matrix.machine.name }}
+    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
+    name: After Crawler
+    runs-on: ubuntu-latest
     steps:
       - name: Clone nestjs-carz-crawler-action.
         uses: actions/checkout@v4
@@ -73,29 +154,28 @@ jobs:
           path: nestjs-carz-crawler-action
           ref: main
 
-      - name: Clone repository nestjs-carz-crawler.
-        uses: actions/checkout@v4
-        with:
-          repository: LibertyCarz/nestjs-carz-crawler
-          token: ${{ secrets.GH_TOKEN }}
-          path: nestjs-carz-crawler
-          ref: main
-
-      - name: Set up Node.js.
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18.12.0
-
-      - name: Install dependencies.
-        working-directory: nestjs-carz-crawler
-        run: npm install --force
-
-      - name: Start NestJS application.
-        working-directory: nestjs-carz-crawler
+      - name: Cleaup.
+        working-directory: nestjs-carz-crawler-action
         run: |
-          node -v
-          echo "const crawler = require('./crawl'); crawler.createData(${{ matrix.machine.chunk }});" > crawler${{ matrix.machine.chunk }}.js
-          node crawler${{ matrix.machine.chunk }}
+          rm -rf data
+          mkdir data
+
+      - name: Loop running.
+        run: |
+          for i in {2..${{ needs.pre-crawler.outputs.number-machines }}}
+          do
+            git clone -b chunk/data-crawler-$i  https://LibertyCarz:${{ secrets.GH_TOKEN }}@github.com/LibertyCarz/nestjs-carz-crawler-action.git chunk-$i
+            cp chunk-$i/$i.cars-data-crawler.csv nestjs-carz-crawler-action/data/
+          done
+
+      - name: Merge files
+        working-directory: nestjs-carz-crawler-action/data
+        run: |
+          for i in {2..${{ needs.pre-crawler.outputs.number-machines }}}
+          do
+            cat $i.cars-data-crawler.csv >> cars-data-crawler.csv
+            echo \n >> cars-data-crawler.csv
+          done
 
       - name: Switch git user to github action.
         working-directory: nestjs-carz-crawler-action
@@ -103,53 +183,21 @@ jobs:
           git config --global user.name "GitHub Actions"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-      - name: Switch to new Branch.
-        working-directory: nestjs-carz-crawler-action
-        run: |
-          git push origin --delete chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
-          git checkout --orphan chunk/data-crawler-${{ matrix.machine.chunk }}
-
-      - name: Copy file.
-        run: cp nestjs-carz-crawler/${{ matrix.machine.chunk }}.cars-data-crawler.csv nestjs-carz-crawler-action/
-
-      - name: Push to chunk/data-crawler-${{ matrix.machine.chunk }}.
+      - name: Push
         working-directory: nestjs-carz-crawler-action
         run: |
           git add -A
           git commit -m "✅ - Save crawler data."
-          git push origin chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
-          git push origin chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
+          git push origin main || echo "Error"
 
-      # - name: Push changes
+      # - name: Remove Chunk branch
+      #   working-directory: nestjs-carz-crawler-action/data
       #   run: |
-      #     du -h ./${{ matrix.machine.chunk }}.cars-data-crawler.csv
-      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
-      #     git config --global user.name "github-actions[bot]"
-      #     git push origin --delete feat-t/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
-      #     git checkout --orphan feat-t/data-crawler-${{ matrix.machine.chunk }}
-      #     git add ./${{ matrix.machine.chunk }}.cars-data-crawler.csv
-      #     git commit -m "✅ - Save crawler data."
-      #     git push origin feat-t/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
-      #     cat ./${{ matrix.machine.chunk }}.cars-data-crawler.csv
-
-  #     - name: Failure notification
-  #       if: ${{ failure() }}
-  #       uses: appleboy/telegram-action@master
-  #       with:
-  #         to: ${{ secrets.TELEGRAM_CHANNEL }}
-  #         token: ${{ secrets.TELEGRAM_TOKEN }}
-  #         message: "💣 - Failure crawling data Khmer24(${{ matrix.machine.chunk }})."
-  # after-crawler:
-  #   needs: [pre-crawler, crawler]
-  #   name: Send Notification Result
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Clone repository
-  #       uses: actions/checkout@v4
-  #       with:
-  #         repository: "LibertyCarz/nestjs-carz-crawler"
-  #         token: ${{ secrets.GH_TOKEN }}
-  #         ref: "main"
+      #     for i in {2..${{ needs.pre-crawler.outputs.number-machines }}}
+      #     do
+      #       cat $i.cars-data-crawler.csv >> cars-data-crawler.csv
+      #       echo \n >> cars-data-crawler.csv
+      #     done
 
   #     - name: Clone as branch
   #       run: |
